-- Care plans: care tasks the admin manages, and their per category / variety rules.
-- A task applies to every plant (audience all), to linked categories / varieties, or is optional (owners add it).
-- A rule sets a category's or one variety's mode (must / optional / off) and interval; source says AI or admin.
-- A plant's own care (the owner's interval, off, or added) is plants.care. No interval anywhere → a
-- "Set schedule" task. Task rows (todos.subcategory) now point at a care task; deleting a task deletes them.

create table care_tasks (
  id text primary key,
  position integer not null,
  name text not null,
  name_he text not null,
  icon text not null check (icon in ('water', 'photo', 'feed', 'repot', 'rotate', 'mist', 'prune', 'clean', 'pest', 'sun')),
  audience text not null check (audience in ('all', 'linked', 'optional')),
  every_days integer check (every_days between 1 and 1095),
  winter_every_days integer check (winter_every_days between 1 and 1095),
  months integer[],
  built_in boolean not null default false
);

create table care_rules (
  id text primary key,
  task_id text not null references care_tasks (id) on delete cascade,
  category_id text not null references catalog_categories (id) on delete cascade,
  subcategory_id text references catalog_subcategories (id) on delete cascade,
  mode text not null check (mode in ('must', 'optional', 'off')),
  every_days integer check (every_days between 1 and 1095),
  winter_every_days integer check (winter_every_days between 1 and 1095),
  months integer[],
  source text not null check (source in ('ai', 'admin'))
);

create unique index care_rules_one_per_scope on care_rules (task_id, category_id, coalesce(subcategory_id, ''));

alter table care_tasks enable row level security;
alter table care_rules enable row level security;

insert into care_tasks (id, position, name, name_he, icon, audience, every_days, winter_every_days, months, built_in) values
  ('water', 0, 'Water', 'השקיה', 'water', 'all', 7, 12, null::integer[], true),
  ('photo', 1, 'Photo check-in', 'צילום מעקב', 'photo', 'all', 30, null, null::integer[], true),
  ('feed', 2, 'Feed', 'דישון', 'feed', 'all', 30, null, '{3,4,5,6,7,8,9}'::integer[], false),
  ('repot', 3, 'Repot', 'העברת עציץ', 'repot', 'all', 365, null, null::integer[], false),
  ('rotate', 4, 'Turn to the light', 'סיבוב לאור', 'rotate', 'linked', 14, null, null::integer[], false),
  ('mist', 5, 'Mist', 'ריסוס', 'mist', 'linked', 3, null, null::integer[], false);

alter table plants add column care jsonb;

alter table todos drop constraint todos_subcategory_check;
alter table todos add constraint todos_care_task_fk foreign key (subcategory) references care_tasks (id) on delete cascade;

-- AI care suggestions for the example catalog (from src/features/todo/careSuggestions.ts), only for the
-- categories and varieties this database has.
insert into care_rules (id, task_id, category_id, subcategory_id, mode, every_days, winter_every_days, months, source)
select v.id, v.task_id, v.category_id, v.subcategory_id, v.mode, v.every_days, v.winter_every_days, v.months, v.source
from (values
  ('water:pothos', 'water', 'pothos', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:pothos', 'feed', 'pothos', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:pothos', 'repot', 'pothos', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('feed:pothos-marble', 'feed', 'pothos', 'pothos-marble'::text, 'must', 45::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('water:monstera', 'water', 'monstera', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:monstera', 'feed', 'monstera', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:monstera', 'repot', 'monstera', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:monstera', 'rotate', 'monstera', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('rotate:monstera-albo', 'rotate', 'monstera', 'monstera-albo'::text, 'must', 21::integer, null::integer, null::integer[], 'ai'),
  ('water:snake-plant', 'water', 'snake-plant', null::text, 'must', 14::integer, 28::integer, null::integer[], 'ai'),
  ('feed:snake-plant', 'feed', 'snake-plant', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:snake-plant', 'repot', 'snake-plant', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('repot:snake-hahnii', 'repot', 'snake-plant', 'snake-hahnii'::text, 'must', 1095::integer, null::integer, null::integer[], 'ai'),
  ('water:peace-lily', 'water', 'peace-lily', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:peace-lily', 'feed', 'peace-lily', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:peace-lily', 'repot', 'peace-lily', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:peace-lily', 'mist', 'peace-lily', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:spider-plant', 'water', 'spider-plant', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:spider-plant', 'feed', 'spider-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:spider-plant', 'repot', 'spider-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:zz', 'water', 'zz', null::text, 'must', 14::integer, 28::integer, null::integer[], 'ai'),
  ('feed:zz', 'feed', 'zz', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:zz', 'repot', 'zz', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:heartleaf', 'water', 'heartleaf', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:heartleaf', 'feed', 'heartleaf', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:heartleaf', 'repot', 'heartleaf', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:pilea', 'water', 'pilea', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:pilea', 'feed', 'pilea', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:pilea', 'repot', 'pilea', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:fiddle', 'water', 'fiddle', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:fiddle', 'feed', 'fiddle', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:fiddle', 'repot', 'fiddle', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:fiddle', 'rotate', 'fiddle', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('rotate:fiddle-bambino', 'rotate', 'fiddle', 'fiddle-bambino'::text, 'must', 28::integer, null::integer, null::integer[], 'ai'),
  ('water:adansonii', 'water', 'adansonii', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:adansonii', 'feed', 'adansonii', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:adansonii', 'repot', 'adansonii', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:satin', 'water', 'satin', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:satin', 'feed', 'satin', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:satin', 'repot', 'satin', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:rubber', 'water', 'rubber', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:rubber', 'feed', 'rubber', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:rubber', 'repot', 'rubber', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:rubber', 'rotate', 'rubber', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:gloriosum', 'water', 'gloriosum', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:gloriosum', 'feed', 'gloriosum', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:gloriosum', 'repot', 'gloriosum', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:gloriosum', 'mist', 'gloriosum', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:clarinervium', 'water', 'clarinervium', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:clarinervium', 'feed', 'clarinervium', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:clarinervium', 'repot', 'clarinervium', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:clarinervium', 'mist', 'clarinervium', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:hoya', 'water', 'hoya', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:hoya', 'feed', 'hoya', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:hoya', 'repot', 'hoya', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:frydek', 'water', 'frydek', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:frydek', 'feed', 'frydek', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:frydek', 'repot', 'frydek', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:frydek', 'mist', 'frydek', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:syngonium', 'water', 'syngonium', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:syngonium', 'feed', 'syngonium', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:syngonium', 'repot', 'syngonium', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:begonia', 'water', 'begonia', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:begonia', 'feed', 'begonia', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:begonia', 'repot', 'begonia', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:begonia', 'mist', 'begonia', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:orchid', 'water', 'orchid', null::text, 'must', 10::integer, 14::integer, null::integer[], 'ai'),
  ('feed:orchid', 'feed', 'orchid', null::text, 'must', 14::integer, null::integer, '{3,4,5,6,7,8,9,10}'::integer[], 'ai'),
  ('repot:orchid', 'repot', 'orchid', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:baby-rubber', 'water', 'baby-rubber', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:baby-rubber', 'feed', 'baby-rubber', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:baby-rubber', 'repot', 'baby-rubber', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:watermelon-pep', 'water', 'watermelon-pep', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:watermelon-pep', 'feed', 'watermelon-pep', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:watermelon-pep', 'repot', 'watermelon-pep', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:ripple-pep', 'water', 'ripple-pep', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:ripple-pep', 'feed', 'ripple-pep', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:ripple-pep', 'repot', 'ripple-pep', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:string-turtles', 'water', 'string-turtles', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:string-turtles', 'feed', 'string-turtles', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:string-turtles', 'repot', 'string-turtles', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:prayer-plant', 'water', 'prayer-plant', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:prayer-plant', 'feed', 'prayer-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:prayer-plant', 'repot', 'prayer-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:prayer-plant', 'mist', 'prayer-plant', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:orbifolia', 'water', 'orbifolia', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:orbifolia', 'feed', 'orbifolia', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:orbifolia', 'repot', 'orbifolia', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:orbifolia', 'mist', 'orbifolia', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:peacock-plant', 'water', 'peacock-plant', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:peacock-plant', 'feed', 'peacock-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:peacock-plant', 'repot', 'peacock-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:peacock-plant', 'mist', 'peacock-plant', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:pinstripe', 'water', 'pinstripe', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:pinstripe', 'feed', 'pinstripe', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:pinstripe', 'repot', 'pinstripe', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:pinstripe', 'mist', 'pinstripe', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:birds-nest-fern', 'water', 'birds-nest-fern', null::text, 'must', 4::integer, 7::integer, null::integer[], 'ai'),
  ('feed:birds-nest-fern', 'feed', 'birds-nest-fern', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:birds-nest-fern', 'repot', 'birds-nest-fern', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:birds-nest-fern', 'mist', 'birds-nest-fern', null::text, 'optional', 2::integer, null::integer, null::integer[], 'ai'),
  ('water:boston-fern', 'water', 'boston-fern', null::text, 'must', 4::integer, 7::integer, null::integer[], 'ai'),
  ('feed:boston-fern', 'feed', 'boston-fern', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:boston-fern', 'repot', 'boston-fern', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:boston-fern', 'mist', 'boston-fern', null::text, 'optional', 2::integer, null::integer, null::integer[], 'ai'),
  ('water:staghorn', 'water', 'staghorn', null::text, 'must', 4::integer, 7::integer, null::integer[], 'ai'),
  ('feed:staghorn', 'feed', 'staghorn', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:staghorn', 'repot', 'staghorn', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:staghorn', 'mist', 'staghorn', null::text, 'optional', 2::integer, null::integer, null::integer[], 'ai'),
  ('water:maidenhair', 'water', 'maidenhair', null::text, 'must', 4::integer, 7::integer, null::integer[], 'ai'),
  ('feed:maidenhair', 'feed', 'maidenhair', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:maidenhair', 'repot', 'maidenhair', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:maidenhair', 'mist', 'maidenhair', null::text, 'optional', 2::integer, null::integer, null::integer[], 'ai'),
  ('water:parlor-palm', 'water', 'parlor-palm', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:parlor-palm', 'feed', 'parlor-palm', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:parlor-palm', 'repot', 'parlor-palm', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:areca-palm', 'water', 'areca-palm', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:areca-palm', 'feed', 'areca-palm', null::text, 'must', 30::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:areca-palm', 'repot', 'areca-palm', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:ponytail-palm', 'water', 'ponytail-palm', null::text, 'must', 21::integer, 45::integer, null::integer[], 'ai'),
  ('feed:ponytail-palm', 'feed', 'ponytail-palm', null::text, 'off', null::integer, null::integer, null::integer[], 'ai'),
  ('repot:ponytail-palm', 'repot', 'ponytail-palm', null::text, 'must', 1095::integer, null::integer, null::integer[], 'ai'),
  ('water:cast-iron', 'water', 'cast-iron', null::text, 'must', 14::integer, 28::integer, null::integer[], 'ai'),
  ('feed:cast-iron', 'feed', 'cast-iron', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:cast-iron', 'repot', 'cast-iron', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:dragon-tree', 'water', 'dragon-tree', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:dragon-tree', 'feed', 'dragon-tree', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:dragon-tree', 'repot', 'dragon-tree', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:dragon-tree', 'rotate', 'dragon-tree', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:corn-plant', 'water', 'corn-plant', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:corn-plant', 'feed', 'corn-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:corn-plant', 'repot', 'corn-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:corn-plant', 'rotate', 'corn-plant', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:inch-plant', 'water', 'inch-plant', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:inch-plant', 'feed', 'inch-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:inch-plant', 'repot', 'inch-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:nerve-plant', 'water', 'nerve-plant', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:nerve-plant', 'feed', 'nerve-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:nerve-plant', 'repot', 'nerve-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:nerve-plant', 'mist', 'nerve-plant', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:aluminum-plant', 'water', 'aluminum-plant', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:aluminum-plant', 'feed', 'aluminum-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:aluminum-plant', 'repot', 'aluminum-plant', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:string-hearts', 'water', 'string-hearts', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:string-hearts', 'feed', 'string-hearts', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:string-hearts', 'repot', 'string-hearts', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:string-pearls', 'water', 'string-pearls', null::text, 'must', 14::integer, 30::integer, null::integer[], 'ai'),
  ('feed:string-pearls', 'feed', 'string-pearls', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:string-pearls', 'repot', 'string-pearls', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:jade', 'water', 'jade', null::text, 'must', 14::integer, 30::integer, null::integer[], 'ai'),
  ('feed:jade', 'feed', 'jade', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:jade', 'repot', 'jade', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:aloe-vera', 'water', 'aloe-vera', null::text, 'must', 14::integer, 30::integer, null::integer[], 'ai'),
  ('feed:aloe-vera', 'feed', 'aloe-vera', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:aloe-vera', 'repot', 'aloe-vera', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:zebra-haworthia', 'water', 'zebra-haworthia', null::text, 'must', 14::integer, 30::integer, null::integer[], 'ai'),
  ('feed:zebra-haworthia', 'feed', 'zebra-haworthia', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:zebra-haworthia', 'repot', 'zebra-haworthia', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:mexican-snowball', 'water', 'mexican-snowball', null::text, 'must', 14::integer, 30::integer, null::integer[], 'ai'),
  ('feed:mexican-snowball', 'feed', 'mexican-snowball', null::text, 'must', 60::integer, null::integer, '{4,5,6,7,8}'::integer[], 'ai'),
  ('repot:mexican-snowball', 'repot', 'mexican-snowball', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:thanksgiving', 'water', 'thanksgiving', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:thanksgiving', 'feed', 'thanksgiving', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:thanksgiving', 'repot', 'thanksgiving', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:mistletoe-cactus', 'water', 'mistletoe-cactus', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:mistletoe-cactus', 'feed', 'mistletoe-cactus', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:mistletoe-cactus', 'repot', 'mistletoe-cactus', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:venus-flytrap', 'water', 'venus-flytrap', null::text, 'must', 3::integer, 7::integer, null::integer[], 'ai'),
  ('feed:venus-flytrap', 'feed', 'venus-flytrap', null::text, 'off', null::integer, null::integer, null::integer[], 'ai'),
  ('repot:venus-flytrap', 'repot', 'venus-flytrap', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:mini-monstera', 'water', 'mini-monstera', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:mini-monstera', 'feed', 'mini-monstera', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:mini-monstera', 'repot', 'mini-monstera', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:hoya-kerrii', 'water', 'hoya-kerrii', null::text, 'must', 10::integer, 18::integer, null::integer[], 'ai'),
  ('feed:hoya-kerrii', 'feed', 'hoya-kerrii', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:hoya-kerrii', 'repot', 'hoya-kerrii', null::text, 'must', 730::integer, null::integer, null::integer[], 'ai'),
  ('water:living-stones', 'water', 'living-stones', null::text, 'must', 21::integer, 45::integer, null::integer[], 'ai'),
  ('feed:living-stones', 'feed', 'living-stones', null::text, 'off', null::integer, null::integer, null::integer[], 'ai'),
  ('repot:living-stones', 'repot', 'living-stones', null::text, 'must', 1095::integer, null::integer, null::integer[], 'ai'),
  ('water:sky-plant', 'water', 'sky-plant', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:sky-plant', 'feed', 'sky-plant', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:sky-plant', 'repot', 'sky-plant', null::text, 'off', null::integer, null::integer, null::integer[], 'ai'),
  ('mist:sky-plant', 'mist', 'sky-plant', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:desert-rose', 'water', 'desert-rose', null::text, 'must', 21::integer, 45::integer, null::integer[], 'ai'),
  ('feed:desert-rose', 'feed', 'desert-rose', null::text, 'off', null::integer, null::integer, null::integer[], 'ai'),
  ('repot:desert-rose', 'repot', 'desert-rose', null::text, 'must', 1095::integer, null::integer, null::integer[], 'ai'),
  ('water:purple-shamrock', 'water', 'purple-shamrock', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:purple-shamrock', 'feed', 'purple-shamrock', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:purple-shamrock', 'repot', 'purple-shamrock', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:flamingo-flower', 'water', 'flamingo-flower', null::text, 'must', 7::integer, 10::integer, null::integer[], 'ai'),
  ('feed:flamingo-flower', 'feed', 'flamingo-flower', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('repot:flamingo-flower', 'repot', 'flamingo-flower', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:bird-paradise', 'water', 'bird-paradise', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:bird-paradise', 'feed', 'bird-paradise', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:bird-paradise', 'repot', 'bird-paradise', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:bird-paradise', 'rotate', 'bird-paradise', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:white-paradise', 'water', 'white-paradise', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:white-paradise', 'feed', 'white-paradise', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:white-paradise', 'repot', 'white-paradise', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:white-paradise', 'rotate', 'white-paradise', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:fatsia', 'water', 'fatsia', null::text, 'must', 7::integer, 12::integer, null::integer[], 'ai'),
  ('feed:fatsia', 'feed', 'fatsia', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:fatsia', 'repot', 'fatsia', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:coffee', 'water', 'coffee', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:coffee', 'feed', 'coffee', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:coffee', 'repot', 'coffee', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:coffee', 'rotate', 'coffee', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:banana', 'water', 'banana', null::text, 'must', 7::integer, 14::integer, null::integer[], 'ai'),
  ('feed:banana', 'feed', 'banana', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:banana', 'repot', 'banana', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('rotate:banana', 'rotate', 'banana', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('water:caladium', 'water', 'caladium', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:caladium', 'feed', 'caladium', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:caladium', 'repot', 'caladium', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:caladium', 'mist', 'caladium', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:african-violet', 'water', 'african-violet', null::text, 'must', 7::integer, 10::integer, null::integer[], 'ai'),
  ('feed:african-violet', 'feed', 'african-violet', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('repot:african-violet', 'repot', 'african-violet', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:cyclamen', 'water', 'cyclamen', null::text, 'must', 7::integer, 10::integer, null::integer[], 'ai'),
  ('feed:cyclamen', 'feed', 'cyclamen', null::text, 'must', 14::integer, null::integer, null::integer[], 'ai'),
  ('repot:cyclamen', 'repot', 'cyclamen', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('water:crystallinum', 'water', 'crystallinum', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:crystallinum', 'feed', 'crystallinum', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:crystallinum', 'repot', 'crystallinum', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:crystallinum', 'mist', 'crystallinum', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:veitchii', 'water', 'veitchii', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:veitchii', 'feed', 'veitchii', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:veitchii', 'repot', 'veitchii', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:veitchii', 'mist', 'veitchii', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:melanochrysum', 'water', 'melanochrysum', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:melanochrysum', 'feed', 'melanochrysum', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:melanochrysum', 'repot', 'melanochrysum', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:melanochrysum', 'mist', 'melanochrysum', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai'),
  ('water:cuprea', 'water', 'cuprea', null::text, 'must', 5::integer, 9::integer, null::integer[], 'ai'),
  ('feed:cuprea', 'feed', 'cuprea', null::text, 'must', 30::integer, null::integer, '{3,4,5,6,7,8,9}'::integer[], 'ai'),
  ('repot:cuprea', 'repot', 'cuprea', null::text, 'must', 365::integer, null::integer, null::integer[], 'ai'),
  ('mist:cuprea', 'mist', 'cuprea', null::text, 'optional', 3::integer, null::integer, null::integer[], 'ai')
) as v (id, task_id, category_id, subcategory_id, mode, every_days, winter_every_days, months, source)
where exists (select 1 from catalog_categories c where c.id = v.category_id)
  and (v.subcategory_id is null or exists (select 1 from catalog_subcategories s where s.id = v.subcategory_id));
